language: node_js
node_js:
- "4.4"
before_script:
- sleep 3
- "node server.js&"
- "npm install auditjs --save-dev"
- sleep 3
- rackup
- sleep 3

script:
- "./node_modules/auditjs/audit.js -p package.json -n"
- sleep 3
- "npm test"