language: node_js
node_js:
- "4.4"
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 5
- "npm run start &"
- sleep 5

script:
- jdk_switcher use oraclejdk8
- sleep 2
- "npm test"