language: node_js
sudo: required
dist: trusty
node_js:
- "10.4"
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 10
- "npm run start &"
- sleep 10

script:
- "npm test"
