language: node_js
sudo: required
dist: trusty
node_js:
- "4.4"
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 10
- "npm run start &"
- "npm install auditjs --save-dev"
- sleep 10

script:
- jdk_switcher use oraclejdk8
- sleep 2
- "npm test"