language: node_js
sudo: required
dist: trusty
node_js:
- "4.4"
before_script:
- sleep 3
- "npm run start &"
- "npm install auditjs --save-dev"
- sleep 3

script:
- jdk_switcher use oraclejdk8
- sleep 3
- "npm test"